[book]
author = "Isabelle Motte"
language = "fr"
src = "src"
title = "UX Design by zabellemotte"

[output.html]
site-url = "/ux-design/"
additional-css = ["theme/css/custom.css"]
no-section-label=true

[output.html.fold]
enable = true
level = 1
